### ISSUE TITLE
POWER8 or Later...

### ISSUE THREAD

**Issue by asanchez500** [nioroso-x3/xmr-stak-power#15]
Will this code run on a ps3? Which is POWER7 right? Which is what you meant by later right? I tried to compile the code but couldn't get CMAKE up to date on the PS3 for PPC64. Have you heard of any one being able to do this at all for ppc64 with cmake?

**Comment by tayore** [comment]
power 7+ has aes acceleration, power  7 dunno and ps3 cell is not power7

**Comment by nioroso-x3** [comment]
PS3 is a power6 derivative. Also it's big endian and too old.
