### ISSUE TITLE
stellite merge

### ISSUE THREAD

**Issue by cryptosven76** [nioroso-x3/xmr-stak-power#16]
Hi,

i love the power port of the miner, do you have any plans to bring them upstream into xmr-stak or periodically merge with xmr-stak main repo ? 
i would like to mine stellite or aeon from time to time but the code doesn't work anymore as they hard hard forks in the meantime. the stellite fork for example is here : 
https://github.com/fireice-uk/xmr-stak/commit/624b4ca870ef184fa3947c8368964e89647d9447

any plans to work on this ? 

thx.

**Comment by madscientist159** [comment]
There's a more up to date version here (not on Github due to recent acquisition of Github)
https://git.raptorengineering.com/git/xmr-stak/

That being said, it hasn't been tested on anything other than Monero right now.  If you could, please try it and let me know if it works!

**Comment by cryptosven76** [comment]
thanks for the tip, i didn't know that , might be good to update the github page so others see it there too :-)
unfortunate, i tried stellite and only get bad shares. i will see if i can find out why ..

thx.

**Comment by nioroso-x3** [comment]
I don't have much time and also don't care about useless forks, so for now I'll only update this if monero breaks or when cryptonight v8 comes.
