### ISSUE TITLE
Drop in hashes

### ISSUE THREAD

**Issue by gokou340** [nioroso-x3/xmr-stak-power#17]
Has there been any issues with drops in hashing? I was at around 3900H/s, and it dropped down to 2300H/s.

I was on SMT=4, but I changed it to 2, and it brought my hashes back up to around 2700H/s. I have 20 cores, and 40 threads going at the moment, and they are getting around 70 Hashes each on SMT=2, when I have them on SMT=4, they get around 30 or so.

Not sure if anyone else was seeing the same thing.

**Comment by madscientist159** [comment]
Have you checked your CPU temps?  The OCC will start to reduce frequency if it detects power / temperature readings that are too high.

**Comment by gokou340** [comment]
Looks like the temps are around 70c for each CPU.

Current MHz is 4023MHz

**Comment by madscientist159** [comment]
Is this a POWER8 or POWER9 box?

**Comment by gokou340** [comment]
This is a Power8 box

**Comment by madscientist159** [comment]
OK, so that's either an AMI BMC or an FSP (is this scale up or scale out?).  Could still be the BMC being too aggressive about slowing things down, if you stop mining and let it cool down, then restart the SMT4 miner, does the H/s pop back up to the 3900 range?

**Comment by gokou340** [comment]
I'm honestly not sure if it is AMI or FSP, but, even when it wasn't running for a week, and I started it back up, it wasn't at the 3900 range.

Would it make sense to try and recompile it?

**Comment by madscientist159** [comment]
Do you have anything else running on the machine that could be causing cache evictions?

**Comment by gokou340** [comment]
Not that I am aware of. It is mainly a test machine, so nothing else is running on it. 

Is there an easy way to tell?

**Comment by madscientist159** [comment]
Take a look at htop,   Are you sure each CPU has memory attached to it?

**Comment by gokou340** [comment]
I do always get Memory Alloc Failed: mmap failed, when I start xmr-stak, but that was happening before, and I just brushed it off.

I am looking at htop, but not sure what I am looking for. Each CPU is at 100%, and memory % is at 0%

**Comment by gokou340** [comment]
So, running "sudo sysctl -w vm.nr_hugepages=128" caused the  Memory Alloc failed to be resolve for about 3/4th of the total CPUs, and the hashes jumped up to 3400H/s, but it still says Memory Alloc failed for for 20 or so threads.

**Comment by gokou340** [comment]
Alright, setting the huge pages to 256 has resolved the issue, and it is going at 3900H/s again.

Not sure why this issue wasn't happening before. Thanks for pointing me in the right direction!
