### ISSUE TITLE
POWER9 performance dropped with shift to BE

### ISSUE THREAD

**Issue by madscientist159** [nioroso-x3/xmr-stak-power#3]
While the POWER8 performance did increase, POWER9 saw a fairly large decrease on the order of several hundred KH/s.  POWER9's SMT is rather amazing at squeezing every bit of performance out of the existing code (watched this via perf), and it doesn't really care about the BE-LE swaps, so the added code to do the BE processing is actually slowing things down on POWER9.

Perhaps BE/LE should be a configuration option?

**Comment by nioroso-x3** [comment]
How weird, so power8 is actually faster per core? I'll add a way to select the code paths then.

**Comment by madscientist159** [comment]
POWER8 and POWER9 are very different µarchs.  POWER8 is normally slower per core, partly because the endian swaps take a lot longer than on POWER9, but POWER8 cores are SMT8 vs. POWER9's SMT4, so a more fair comparison would be 2 POWER9 cores against one POWER8 core (since SU P9 chips gang the slices together to create a P9 SMT8 core, I think this is a valid way to handle things).   Also, POWER9 doesn't have the penalties for endian swapping (at least on this workload) so it makes no sense to force it into BE mode (which, when viewed in disassembly, typically adds instructions into the hot loop).

The current peak for POWER9 SO is SMT4 with three threads per core.  The BE code is faster than the LE code when comparing performance on POWER9 SMT1 or SMT2, but slower overall compared to this optimized SMT4 configuration.  I expect this to change somewhat on the production parts.

**Comment by nioroso-x3** [comment]
Ok, I added an option in the config file "little_endian_mode". Set to true for POWER9, false for POWER8.
