### ISSUE TITLE
undefined reference to `vtable for std::__future_base::_State_base'

### ISSUE THREAD

**Issue by Lem3xcol** [nioroso-x3/xmr-stak-power#4]
HI, 

I'm, trying to compile in a Power8 LPAR. When I'm compiling, I'm getting this warning after cmake:

> 
         link library [libssl.so] in /usr/lib64 may be hidden by files in:
         /opt/at10.0/lib64
         link library [libcrypto.so] in /usr/lib64 may be hidden by files in:
         /opt/at10.0/lib64
         Some of these libraries may not be found correctly.
> 

But despite that, the build files are generated. When I run make, I'm getting this:

> 
     CMakeFiles/xmr-stak-power.dir/executor.cpp.o:(.toc+0x8): undefined reference to `vtable for         
     std::__future_base::_State_base'
     collect2: error: ld returned 1 exit status
     make[2]: *** [bin/xmr-stak-power] Error 1
     make[1]: *** [CMakeFiles/xmr-stak-power.dir/all] Error 2
     make: *** [all] Error 2
>

How this error could be fixed?

My O.S. is RedHat Linux 7.4 LE.

Thank you for the help. Sorry about my bad english.

Regards, 

Luis M.

**Comment by nioroso-x3** [comment]
How did you install the AT tools?
I have only tested installing them through yum, using Centos 7.

Also, did you install the required devel libraries? They are the same ones used by the parent project, xmr-stak-cpu, hwloc-devel libmicrohttpd-devel and openssl-devel.

And what is the output of "echo $LD_LIBRARY_PATH" ?
I think it might something related to your systems ld.conf configuration.

**Comment by nioroso-x3** [comment]
Closing this, I guess it was a problem in the users environment.
