### ISSUE TITLE
Power7

### ISSUE THREAD

**Issue by DoktorCranium** [nioroso-x3/xmr-stak-power#7]
Hi, did you guys ever consider changes to the xmr-stak-power7 code to support this on big-endian older power7 architecture ?

**Comment by nioroso-x3** [comment]
I have read some POWER7 documentation, but it seems its crypto units require kernel calls and there's only one per socket. I don't know if it would be worth it.
Also I don't have access to any big endian powerpc besides my quad G5 and a mac mini G4.

**Comment by DoktorCranium** [comment]
Do you thin it would be worth to port it to Power7  MMD 64 CPU ? It has a potential I believe.

**Comment by DoktorCranium** [comment]
IBM Power7+ (9117 MMD ) Power 770
How could I contact you apart from github chat ?
I have tried the above code and it compiles fine on the Power7+ machine via the IBM compiler toolkit. Problem is that the binary obviously crashes.

**Comment by yuhong** [comment]
Would you be willing to do the AES in software or what?

**Comment by DoktorCranium** [comment]
I have just chewed through some Power7 documentation, so there is no Power7 AES instruction set in the CPU .. that is only on Power8 and Power9. Guess this makes no sense to do it in software :) Sorry for he dumb question.

**Comment by nioroso-x3** [comment]
No problem.
